app.security.enabled: true
#server:
#  port: 8080

spring.security.user.name: admin
spring.security.user.password: 123

yakworks:
  gorm:
    query:
      max: 50
      timeout: 60

app:
  security:
    users:
      admin:
        query:
          max: 100
          timeout: 120
