#debug: true
spring.main.lazy-initialization: true
spring.main.allow-bean-definition-overriding: true
#server.port: 8081

spring.config.import: classpath:./security.yml, classpath:./grails.yml

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
    # org.springframework.security: DEBUG
    # org.springframework.security.web: TRACE
    # org.springframework.security.authentication: TRACE
    # grails.plugins.DefaultGrailsPluginManager: ERROR
    # TURN ON for benchmarks
    # org.hibernate: INFO
    # for stats and sql logging
    # org.hibernate.stat: DEBUG
    org.hibernate.SQL: ERROR
    # this one is very noisy but if neede will show the values passed to sql statements
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    yakity.security: TRACE

---

grails:
  profile: rest-api
  cache:
    enabled: false
  # NOTE: reminder that anything in config.locations wins and ovewrites whats in this config
  config:
    locations:
      - "classpath:restapi-config.yml"
      - "classpath*:restapi/rally/*.yml"

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

#  servlet:
#    context-path: /api
management:
  #  health:
  #    diskspace:
  #      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,liveness,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  jmx:
    enabled: true

---

app:
  resources:
    # project.rootProjectDir comes from project.rootProjectDir system prop setup in gradle or defaults to . if not set and running from intellij
    rootLocation: "${project.rootProjectDir}/examples/resources"
    tempDir: "./build/rootLocation/tempDir"
    attachments.location: 'attachments'

---

hibernate:
  generate_statistics: true
  format_sql: false
  schema_management_tool: 'yakworks.hibernate.schema.SimpleSchemaManagementTool'
  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: true
    provider_class: 'com.hazelcast.cache.HazelcastCachingProvider'
    region.factory_class: 'com.hazelcast.hibernate.HazelcastCacheRegionFactory'
    hazelcast:
#      use_native_client: true
      instance_name: hz-member-1
      shutdown_on_session_factory_close: false
  jdbc:
    time_zone: 'UTC'

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:
  type: com.zaxxer.hikari.HikariDataSource
  dbCreate: create-drop
  url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#  url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#  properties:
#    defaultTransactionIsolation: 2 # Connection.TRANSACTION_READ_COMMITTED
#    transactionIsolation: "TRANSACTION_READ_COMMITTED" # Hikari needs this
