#debug: true
spring.main.lazy-initialization: true
spring.main.allow-bean-definition-overriding: true
#server.port: 8081
server.servlet.context-path: /api

spring.config.import: >-
  classpath:config/security.yml,
  classpath:config/grails.yml,
  classpath:config/datasource.yml,
  classpath:config/foo.yml,
  optional:file://${app.resources.rootLocation}/application.yml

api.config.import: classpath:/restapi-config.yml,classpath*:/restapi/**/*.yml

foo:
  message: "from rally-api/application.yml"

#spring.cache.cache-names: customers,customersSearch
#spring.cache.type: hazelcast
#spring:
#  cache:
#    type: CAFFEINE # can set to NONE for testing dev
#    caffeine:
#      spec: initialCapacity=10,maximumSize=100,expireAfterAccess=1h

logging:
  level:
    root: info
    org.springframework: INFO
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
    #org.springframework.security: DEBUG
    #org.springframework.boot.autoconfigure: DEBUG
    yakworks.rally.api.rally.OrgController: DEBUG
    yakworks.rally.api.OrgCrudApi: DEBUG
    yakworks.spring.hazelcast: DEBUG
    org.apache.ignite.internal.IgniteKernal: INFO

    #gorm.tools.mango.MangoDetachedCriteria: DEBUG

#    gorm.tools.mango.MangoBuilder: DEBUG
    org.hibernate: OFF # turns off all
    # org.springframework.security.web: TRACE
    # org.springframework.security.authentication: TRACE
    # grails.plugins.DefaultGrailsPluginManager: ERROR
    # TURN ON for benchmarks
    # org.hibernate: INFO
    # for stats and sql logging
    # org.hibernate.stat: DEBUG
    #org.hibernate.SQL: DEBUG
    # this one is very noisy but if neede will show the values passed to sql statements
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #yakity.security: TRACE

---

grails:
  profile: rest-api
  cache:
    enabled: false
  # NOTE: reminder that anything in config.locations wins and ovewrites whats in this config
#  config:
#    locations:
#      - "classpath:restapi-config.yml"
#      - "classpath*:restapi/rally/*.yml"

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'


management:
  endpoints:
    enabled-by-default: true
    web:
      # base-path: /actuator
      exposure:
        include: '*'
#        include: health,info,liveness,metrics,caches
  jmx:
    enabled: true

management.info.env.enabled: true
management.endpoint.metrics.enabled: true

# enables readiness and liveness
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: when-authorized
management.endpoint.health.show-components: when-authorized

---

app:
  resources:
    # project.rootProjectDir comes from project.rootProjectDir system prop setup in gradle or defaults to . if not set and running from intellij
    rootLocation: "${project.rootProjectDir}/examples/resources"
    tempDir: "./build/rootLocation/tempDir"
    attachments.location: 'attachments'

# enable multiple views resolvers by removing suffix and restricting viewNames so it flows through to hbs or mustache
#spring.thymeleaf.view-names: "*.html"
#spring.thymeleaf.suffix: ""
#spring.thymeleaf.template-resolver-order: 0

# uncomment starter in build.gradle to activate handlebars
handlebars.enabled: true
# handlebars.failOnMissingFile: false

ignite:
  igniteInstanceName: ${info.app.name}-server-${random.uuid}
  #workDirectory: "${project.projectDir}/build/ignite"
# These blow up on converter. No converter found org.grails.config.NavigableMap
#  communicationSpi:
#    localPort: 5555
#  dataStorageConfiguration:
#    defaultDataRegionConfiguration:
#      initialSize: 10485760 #10MB
#    dataRegionConfigurations:
#      - name: my-dataregion
#        initialSize: 104857600 #100MB
#  cacheConfiguration:
#    - name: accounts
#    - name: my-cache2
