---
grails:
  profile: rest-api
  codegen:
    defaultPackage: restify
  cache:
    enabled: false

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false
server:
  port: 8081
#  servlet:
#    context-path: /api
management:
  #  health:
  #    diskspace:
  #      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      base-path: /api/actuator
      exposure:
        include: health,info,liveness,metrics
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  jmx:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
    com.hazelcast: INFO
    yakworks.security.shiro: DEBUG
    # TURN ON for benchmarks
    # org.hibernate: INFO
    # for stats and sql logging
    # org.hibernate.stat: DEBUG
    # org.hibernate.SQL: DEBUG
    # this one is very noisy but if neede will show the values passed to sql statements
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---

grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8

---

hibernate:
  generate_statistics: true
  format_sql: false
  schema_management_tool: 'gorm.tools.hibernate.schema.CustomSchemaManagementTool'
  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    provider_class: 'com.hazelcast.cache.HazelcastCachingProvider'
    region.factory_class: 'com.hazelcast.hibernate.HazelcastCacheRegionFactory'
    hazelcast:
#      use_native_client: true
      instance_name: hz-member-1
      shutdown_on_session_factory_close: false
  jdbc:
    time_zone: 'UTC'

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:
  type: com.zaxxer.hikari.HikariDataSource

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  test:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      properties:
        defaultTransactionIsolation: 2 # Connection.TRANSACTION_READ_COMMITTED
        transactionIsolation: "TRANSACTION_READ_COMMITTED" # Hikari needs this
