# used in the build.sh as well as gradle
# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Gorm Tools Grails Plugin
description: Plugin tools Grails/Gorm - repository data services, json query language, fast data binder
author: Yak.Works

project:
  # this is the owner/repo github name
  fullName: yakworks/gorm-tools
  # list of subproject dirs used to spin through, build the checksum and consolidate the test reports for circle
  subprojects: gorm-tools gorm-tools-rest gorm-tools-security rally-domain examples/restify examples/testify

# app info, assumes that there is one main deployable app per project which is the best practice. You can always make more
# bash converts to upper and dots to underscore. for example app.name will be APP_NAME
app:
  name: restify
  key: ${APP_NAME}-${VERX_NO_DOTS}
  dir: examples/restify
  jar: ${APP_DIR}/build/libs/${APP_NAME}-${BUILD_VERSION}.jar
  docker_url: yakworks/gorm-tools:${APP_KEY}
  kub:
    nfs: 10.42.2.176
    namespace: gorm-tools
    ingress_url: ${APP_KEY}.9ci.io

release:
  changelog: docs/release-notes.md
  branch_regex: master|release/.+

team:
  developers: ['basejump: Joshua Burnett', 'snimavat: Sudhir Nimavat', 'alexeyzvegintcev: Alexey']

maven:
  repoUrl: http://repo.9ci.com/public-libs
  snapshotUrl: http://repo.9ci.com/oss-snapshots

codenarc:
  main:
    excludes: ['**/BootStrap.*', '**/UrlMappings.*']

spotless:
  groovy:
    excludes:
      - '**/conf/**/*.groovy'
      - '**/org/grails/**/*.groovy'
