# used in the build.sh as well as gradle
# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml

# shipkit converts these keys to uppercase and dots to underscore. for example app.name will be APP_NAME

title: Gorm Tools Grails Plugin
description: Plugin tools Grails/Gorm - repository data services, json query language, fast data binder
author: Yak.Works

project:
  # this is needed for url in pom for jar lib, doesnt pick up defaults from git
  fullName: yakworks/gorm-tools
  # list of subproject dirs used to spin through, build the checksum and consolidate the test reports for circle
  subprojects: gorm-tools gorm-tools-rest gorm-tools-security rally-domain examples/restify examples/testify

# app info, assumes that there is one main deployable app per project which is the best practice.
# But you can always make more and create a .env or .sh and call 'make foo env=deploy/custom.env
# versions snapshot, dev, stable
# restify:current stable, restify-dev: latest dev release, restify-snapshot: most recent snapshot
# only when we have an old version will it have that appened.
# app_key standard to <app name>-<env>-<short version>
# so when app_name=restify, app_env=dev short_ver=10 then its restify-dev,
# if VERSION_POSTFIX get set then it would be restify-snapshot

app:
  name: restify
  key: ${APP_NAME}${VERSION_POSTFIX}
  jar: examples/restify/build/libs/${APP_NAME}-${BUILD_VERSION}.jar
  docker:
    src: ./deploy/docker
    url: yakworks/gorm-tools:${APP_KEY}
  kube:
    src: ./deploy/kube
    nfs: 10.42.2.176
    namespace: yakworks
    ingress_url: ${APP_KEY}.9ci.io

bot:
  email: 9cibot@9ci.com
  sign_commits: true

vault:
  repo: 9ci/vault

release:
  # after release, will set version.properties back to snapshot=true or releasable=false
  reset_flag: true
  # changelog: CHANGELOG.md

# publish:
#   branch_regex: master|dev|release/.+

team:
  developers: ['basejump: Joshua Burnett', 'snimavat: Sudhir Nimavat', 'alexeyzvegintcev: Alexey']

maven:
  repoUrl: http://repo.9ci.com/public-libs
  snapshotUrl: http://repo.9ci.com/oss-snapshots

codenarc:
#  toolVersion: 2.2.0
  main:
    excludes: ['**/BootStrap.*', '**/UrlMappings.*']

spotless:
  groovy:
    excludes:
      - '**/conf/**/*.groovy'
      - '**/org/grails/**/*.groovy'
