# FOR TESTING ONLY, reminder that application.yml does not get published with jar
spring:
  config:
    import: classpath:./gorm/tools/datasource-test.yml,
            classpath:./security-configs/anonymous.yml

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
