# This is for VSCode `REST Client` plugin. Install it and use it, it rocks
# @host = https://rcm-dev-api.9ci.io
@host = http://localhost:8080
@base_url = {{host}}/api/rally/org
# @host = localhost:8080
@contentType = application/json
# @token = qdoiu426fbaeequ4baj6frghasckor9n

# @name login
POST {{host}}/api/login
Content-Type: application/json

{"username":"admin","password":"123Foo"}

###
@token = {{login.response.body.$.access_token}}

### Get Customers
GET {{base_url}}
Authorization: Bearer {{token}}

### get customers query
GET {{base_url}}?q=org%
Authorization: Bearer {{token}}

### post/create and put/update

# @name post_it
POST {{base_url}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "num": {{$randomInt 100 10000}},
  "name": "Test"
}

### Get it

@created_id = {{post_it.response.body.$.id}}

GET {{base_url}}/{{created_id}}
Authorization: Bearer {{token}}

### update it

PUT {{base_url}}/{{created_id}}
Authorization: Bearer {{token}}

{
  "name": "TestUpdate"
}
