---
grails:
  profile: rest-api
  codegen:
    defaultPackage: restify
  config:
    locations: ["classpath:restapi-config.yml", "classpath*:restapi/*.yml"]

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
#  profiles:
#    active: local
#  config:
#    additional-location:

  main:
    banner-mode: "off"
    lazy-initialization: true
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

foo:
  message: from local

---

#foo:
#  message: from base

pprop: got ${foo.message}

grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8

---

spring.config.import: classpath:./datasource.yml
#hibernate:
#  format_sql: false
#  schema_management_tool: 'gorm.tools.hibernate.schema.CustomSchemaManagementTool'
#  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
#  dialect: 'gorm.tools.hibernate.ExtendedH2Dialect'
#  show_sql: false
#  cache:
#    use_second_level_cache: false
#  jdbc:
#    time_zone: 'UTC'
#
#dataSource:
#  pooled: true
#  jmxExport: true
#  driverClassName: org.h2.Driver
#  username: sa
#  password:
#  type: com.zaxxer.hikari.HikariDataSource
#  dbCreate: create-drop
#  url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

---

grails:
 plugin:
   springsecurity:
     active: true
     rest:
       active: false
     securityConfigType: InterceptUrlMap
     interceptUrlMap: [ { pattern: '/**', access: ['IS_AUTHENTICATED_ANONYMOUSLY'] } ]

---

#projectRoot: ${gradle.rootProjectDir}
app:
  resources:
    rootLocation: "${gradle.rootProjectDir}/examples/resources"
    tempDir: "./build/rootLocation/tempDir"
    attachments.location: 'attachments'
