---
grails:
  profile: rest-api
  codegen:
    defaultPackage: restify
  config:
    locations:
      - classpath:restapi-config.yml

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

---

grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8

---

hibernate:
  format_sql: false
  schema_management_tool: 'yakworks.rally.ddl.CustomSchemaManagementTool'
  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    provider_class: 'org.hibernate.cache.EhCacheProvider'
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  jdbc:
    time_zone: 'UTC'

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:
  type: com.zaxxer.hikari.HikariDataSource

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  test:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      properties:
        defaultTransactionIsolation: 2 # Connection.TRANSACTION_READ_COMMITTED
        transactionIsolation: "TRANSACTION_READ_COMMITTED" # Hikari needs this
