spring:
  profiles:
    group:
      development: dev
      production: prod
  config:
    import: classpath:./datasource.yml, classpath:./testify-defaults.yml

logging:
  level:
    root: INFO
    #    org.springframework: WARN
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
    restify.Application: INFO

app:
  resources:
    # project.rootProjectDir comes from project.rootProjectDir system prop setup in gradle or defaults to . if not set and running from intellij
    rootLocation: "${project.rootProjectDir}/examples/resources"
    tempDir: "./build/rootLocation/tempDir"
    attachments.location: 'attachments'
---

grails:
  profile: foo
  codegen:
    defaultPackage: restify
  config:
    locations: ["classpath:restapi-config.yml", "classpath*:restapi/*.yml"]

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  groovy:
    template:
      check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
  enabled: false
  jmx:
    enabled: true

foo:
  message: from default application.yml

---

#foo:
#  message: from base

pprop: foo.message in main is ${foo.message}

grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8

---

grails:
 plugin:
   springsecurity:
     active: true
     rest:
       active: false
     securityConfigType: InterceptUrlMap
     interceptUrlMap: [ { pattern: '/**', access: ['IS_AUTHENTICATED_ANONYMOUSLY'] } ]

---

#spring.config.activate.on-profile: dev
#spring.config.import: classpath:testify-dev.yml

