foo:
  message: from application-prod.yml

dataSource:
  dbCreate: create-drop
  url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  properties:
    defaultTransactionIsolation: 2 # Connection.TRANSACTION_READ_COMMITTED
    transactionIsolation: "TRANSACTION_READ_COMMITTED" # Hikari needs this
