---
restApi:
  project: # project already exists as a project controller so this just configures it
    includes:
      list: ['id', 'num', 'name', 'billable']
      picklist: ['id', 'num', 'name']

  book: # basic example where all the defaults come either from domain or their stock
    entityClass: restify.Book

  org:
    entityClass: yakworks.rally.orgs.model.Org
    includes:
      get: ['*', 'info.*']
      picklist: ['id', 'name']
    form:
      - key: reasonCode
        type: select
        selectOptions:
          dataApiKey: orgType
          dataApiParams:
            or:
              - name: 'name'
              - name: 'name2'

  task:
    entityClass: yakworks.gorm.testing.model.Taskify
    qSearch: ['name', 'note']
    includes:
      get: ['*', 'project.*']

  user:
    entityClass: gorm.tools.security.domain.AppUser
    qSearch: [ 'username', 'name' ]
    includes:
      get: [ '*', 'roles.id', 'roles.name' ]
