package restify

import gorm.tools.rest.testing.RestApiFuncSpec
import grails.testing.mixin.integration.Integration
import grails.transaction.Rollback

@Integration
@Rollback
class AppUserRestApiSpec extends RestApiFuncSpec {

    Class<AppUser> domainClass = AppUser
    // set to true if you have configured the _error.gson or controller
    // to return application/vnd.error vs application/json
    boolean vndHeaderOnError = false

    String getResourcePath() {
        "${baseUrl}api/appUser"
    }

    //data to force a post or patch failure
    Map getInvalidData() { [userName: null] }

    //Override if you don't want to use the autogenerated Example data.
    Map getInsertData() { [userName: "project", magicCode: "x123"] }

    Map getUpdateData() { [userName: "project Update", magicCode: "x123u"] }

}
