grails:
  profile: plugin
  codegen:
    defaultPackage: taskify.domains.plugin
info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

hibernate:
  format_sql: false
  schema_management_tool: 'yakworks.rally.ddl.CustomSchemaManagementTool'
  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: false
    provider_class: 'org.hibernate.cache.EhCacheProvider'
    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  jdbc:
    time_zone: 'UTC'

dataSource:
  type: com.zaxxer.hikari.HikariDataSource
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:

environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  test:
    dataSource:
      dbCreate: create-drop
      url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  production:
    dataSource:
      dbCreate: none
      url: jdbc:h2:./prodDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

