# Use Httyak plugin https://github.com/AnWeber/vscode-httpyac
@host = http://localhost:8081
@base_url = {{host}}/api
@contentType = application/json
@Authorization=Bearer {{login.access_token}}
# @Authorization=token 1234

### ****** IF SEC ENABLED RUN THIS FIRST TO LOGIN*******
# @name login
POST {{base_url}}/login
Content-Type: application/json

{"username":"admin","password":"123Foo"}

### ****** LOGIN as CUSTOMER*******
# @name login
POST {{base_url}}/login
Content-Type: application/json

{"username":"cust","password":"123Foo"}

### VALIDATE AUTH
# @ref login
GET {{base_url}}/validate
Authorization: Bearer {{login.access_token}}
{{
  test.status(200);
}}

### logout
# @ref login
POST {{base_url}}/logout
Authorization: Bearer {{login.access_token}}
{{
  test.status(200);
}}

### Org
# @no-cookie-jar
GET {{base_url}}/rally/org
Authorization: {{Authorization}}

### Org
# @no-cookie-jar
GET {{base_url}}/rally/org
Authorization: {{Authorization}}


### Org
GET {{base_url}}/rally/contact
Authorization: {{Authorization}}

### Org/contact list
# @ref login
GET {{base_url}}/rally/org/1/contact.csv
Authorization: Bearer {{login.access_token}}

### Org/contact get
# @ref login
GET {{base_url}}/rally/org/1/contact/1
Authorization: Bearer {{login.access_token}}

### Contact list
# @ref login
GET {{base_url}}/rally/contact
Authorization: Bearer {{login.access_token}}

### Contact get
# @ref login
GET {{base_url}}/rally/contact/1
Authorization: Bearer {{login.access_token}}

### Health
GET {{base_url}}/actuator/health

### Contact list
# @ref login
GET {{base_url}}/rally/role/1
Authorization: Bearer {{login.access_token}}


GET {{base_url}}/appInfo

### Contact list
# @ref login
GET {{host}}/hazel
Authorization: {{Authorization}}
