# Use Httyak plugin https://github.com/AnWeber/vscode-httpyac
@host = http://localhost:5701
@base_url = {{host}}/hazelcast
@contentType = application/json

### See https://docs.hazelcast.com/hazelcast/5.3/maintain-cluster/rest-api
### cluster state
GET {{base_url}}/health/cluster-state

### check ize
GET {{base_url}}/health/cluster-size

### node state
GET {{base_url}}/health/node-state

### maps
GET {{base_url}}/rest/cluster

### maps
GET {{base_url}}/rest/maps/
