# Use Httyak plugin https://github.com/AnWeber/vscode-httpyac
@host = http://localhost:8080
@base_url = {{host}}/api
@contentType = application/json
@Authorization=Bearer {{login.access_token}}
# @Authorization=token 1234

### ****** IF SEC ENABLED RUN THIS FIRST TO LOGIN, see login.http for more*******
# @name login
POST {{base_url}}/login
Content-Type: application/json

{"username":"admin","password":"123"}

### basic auth
# @name login
POST http://admin:123@localhost:8080/api/token
Content-Type: application/json

### VALIDATE WTF
# @ref login
GET {{base_url}}/validate
Authorization: {{Authorization}}

### Org
# @ref login
GET {{base_url}}/rally/org
Authorization: {{Authorization}}

### Org get first
# @no-cookie-jar
GET {{base_url}}/rally/org/199999
Authorization: {{Authorization}}

### Org xlsx
# @no-cookie-jar
GET {{base_url}}/rally/org?format=xlsx
Authorization: {{Authorization}}


### Org
GET {{base_url}}/rally/contact
Authorization: {{Authorization}}

### Org/contact list
# @ref login
GET {{base_url}}/rally/org/1/contact.csv
Authorization: {{Authorization}}

### Org/contact get
# @ref login
GET {{base_url}}/rally/org/1/contact/1
Authorization: Bearer {{login.access_token}}

### Contact list
# @ref login
GET {{base_url}}/rally/contact
Authorization: Bearer {{login.access_token}}

### Contact get
# @ref login
GET {{base_url}}/rally/contact/1
Authorization: Bearer {{login.access_token}}

### Contact list
# @ref login
GET {{base_url}}/rally/role/1
Authorization: Bearer {{login.access_token}}

## 404
GET http://localhost:8080/info/urlMappings

## 500 error
GET http://localhost:8080/info/urlMappings

GET http://localhost:8080/info/urlMappings

### Contact list
# @ref login
GET {{host}}/api/hazel
Authorization: {{Authorization}}

### Health
GET {{host}}/api/actuator/health

### readiness
GET {{base_url}}/actuator/health/readiness

### liveness
GET {{base_url}}/actuator/health/liveness
