
spring.config.import: classpath:./gorm/tools/datasource-test.yml

#spring.main.lazy-initialization: true
spring.main.allow-bean-definition-overriding: true

logging:
  level:
    root: WARN
    org.springframework: WARN
    #    org.hibernate.orm.deprecation: INFO # turns on deprecation notices
    # uncomment to turn on sql logging
    # org.hibernate.stat: DEBUG
    # org.hibernate.SQL: DEBUG
    # shows the sql parameters
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  resources:
    rootLocation: "./build/rootLocation"
    tempDir: "./build/rootLocation/tempDir"
    attachments.location: 'attachments'

  # see MailConfig class
  mail:
    enabled: true
    # the testing domain for mailgun, need to go here and add your email to be verified
    # https://app.mailgun.com/app/sending/domains/sandbox597489f7971340b583ee0a01ba7d313a.mailgun.org
    default-domain: sandbox597489f7971340b583ee0a01ba7d313a.mailgun.org

  # Organizations setup
#  orgs:
#    partition:
#      enabled: true # means there can be more than one.
#      type: Division
#
#    members:
#      enabled: true # defaults to true
#      dimension: [ Customer, Branch, Division, Company ]

    # Uncomment this to do a real email test and add the key, this will disable the TestMailService and use the real one.
#    mailgun:
#      enabled: true
#      # ⁉️⛔️DO NOT CHECK THE private-api-key INTO GITHUB OR MAILGUN WILL SUSPEND US!!! ⁉️⛔️
#      private-api-key: 9c7c1eddae....
