
spring.config.import: classpath:./gorm/tools/datasource-test.yml

#spring.main.lazy-initialization: true
spring.main.allow-bean-definition-overriding: true

logging:
  level:
    root: WARN
    org.springframework: WARN
    #    org.hibernate.orm.deprecation: INFO # turns on deprecation notices
    # uncomment to turn on sql logging
#    org.hibernate.stat: DEBUG
#    org.hibernate.SQL: DEBUG
#     shows the sql parameters
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  resources:
    rootLocation: "./build/rootLocation"
    tempDir: "./build/rootLocation/tempDir"
    attachments.location: 'attachments'

  # see MailConfig class
  mail:
    enabled: true
    default-domain: mg.greenbill.io
    mailgun:
      # enabled: true
      private-api-key: zzz

