---
hibernate:
  generate_statistics: true
  format_sql: false
  schema_management_tool: 'yakworks.hibernate.schema.SimpleSchemaManagementTool'
  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
  dialect: 'yakworks.gorm.hibernate.dialect.ExtendedH2Dialect'
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: true
    use_query_cache: true
#    provider_class: 'com.hazelcast.cache.HazelcastCachingProvider'
    region.factory_class: 'com.hazelcast.hibernate.HazelcastCacheRegionFactory'
    hazelcast:
      # use_native_client: true
      instance_name: hz-member-1
      shutdown_on_session_factory_close: false
  jdbc:
    time_zone: 'UTC'

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:
  type: com.zaxxer.hikari.HikariDataSource
  dbCreate: create-drop
  url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#  properties:
#    defaultTransactionIsolation: 2 # Connection.TRANSACTION_READ_COMMITTED
#    transactionIsolation: "TRANSACTION_READ_COMMITTED" # Hikari needs this
