app:
  security:
    # default tokenType it either store or jwt
    tokenType: store
    jwt:
      # default jwt type (either HS256 or RS256
      type: HS256
      # seret for Symmetric HS256 tokens
      secret: kNe%4&RYDhNh
      # for RS256
      privateKey: classpath:jwt/app.key
      publicKey: classpath:jwt/app.pub

#spring.security.saml2.relyingparty.registration.okta.singlelogout.binding: POST
#spring.security.saml2.relyingparty.registration.okta.singlelogout.response-url: "{baseUrl}/logout/saml2/slo"
#spring.security.saml2.relyingparty.registration.okta.assertingparty.metadata-uri: https://dev-86352402.okta.com/app/exk7dad4ucR8cUZXE5d7/sso/saml/metadata

---

spring:
  security:
    oauth2:
      client:
        registration:
#          login-client:
#            provider: spring
#            client-id: login-client
#            client-secret: openid-connect
#            client-authentication-method: client_secret_basic
#            authorization-grant-type: authorization_code
#            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/login-client
#            scope: openid,profile
#            client-name: Spring
          github:
            client-id: b8d2...
            client-secret: 387e...
          okta:
            client-id: 0o...
            client-secret: JxSy...
        provider:
          okta:
            authorization-uri: https://dev-86091574.okta.com/oauth2/v1/authorize
            token-uri: https://dev-86091574.okta.com/oauth2/v1/token
            user-info-uri: https://dev-86091574.okta.com/oauth2/v1/userinfo
            jwk-set-uri: https://dev-86091574.okta.com/oauth2/v1/keys
#          spring:
#            authorization-uri: http://localhost:9000/oauth2/authorize
#            token-uri: http://localhost:9000/oauth2/token
#            jwk-set-uri: http://localhost:9000/oauth2/jwks
