app.security.jwt.privateKey: classpath:jwt/app.key
app.security.jwt.publicKey: classpath:jwt/app.pub

spring.security.saml2.relyingparty.registration.okta.singlelogout.binding: POST
spring.security.saml2.relyingparty.registration.okta.singlelogout.response-url: "{baseUrl}/logout/saml2/slo"
spring.security.saml2.relyingparty.registration.okta.assertingparty.metadata-uri: https://dev-86091574.okta.com/app/exk6q8gnhjgmEfqI65d7/sso/saml/metadata

