spring.transaction.default-timeout: 60

# Longer query timeout for specific users.
yakworks:
  gorm:
    timeouts:
      query: 60
      transaction: 120
      users:
        admin:
          query-timeout: 120
