
# Longer query timeout for specific users.
yakworks:
  gorm:
    query:
      max: 100
      timeout: 60
      exportMax: 1000

app:
  security:
    users:
      system:
        query:
          max: 500
          timeout: 120
