
# Longer query timeout for specific users.
yakworks:
  gorm:
    query:
      max: 100
      timeout: 60
      exportMax: 1000

app:
  security:
    users:
      system:
        query:
          max: 500
          timeout: 120

logging:
  level:
    root: WARN
    org.springframework: WARN
    #    org.hibernate.orm.deprecation: INFO # turns on deprecation notices
    # uncomment to turn on sql logging
    # org.hibernate.stat: DEBUG
    #org.hibernate.SQL: DEBUG
    # shows the sql parameters
    # org.hibernate.type.descriptor.sql.BasicBinder: TRACE
