spring.config.import: classpath:./gorm/tools/datasource-test.yml

info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
spring:
  main:
    banner-mode: "off"
    lazy-initialization: true
  groovy:
    template:
      check-template-location: false

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
    # uncomment to turn on sql logging
    # org.hibernate.stat: DEBUG
    # org.hibernate.SQL: DEBUG

dataSource:
  properties:
    # By default sql server has default isolation read commited, mysql has repeatable read
    # This sets default isolation to TRANSACTION_READ_COMMITTED. so its consistent
    defaultTransactionIsolation: 2 # Connection.TRANSACTION_READ_COMMITTED
    transactionIsolation: TRANSACTION_READ_COMMITTED #Hikari needs this

app:
  resources:
    rootLocation: "${project.rootProjectDir}/examples/resources"
    tempDir: "./build/rootLocation/tempDir"

yakworks:
  gorm:
    async:
      pool-size: 2
    idGenerator:
      start-value: 999
